//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer.InformationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InformationService.IInformationService")]
    public interface IInformationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformationService/GetDemographicsUsingDBWithConfig", ReplyAction="http://tempuri.org/IInformationService/GetDemographicsUsingDBWithConfigResponse")]
        System.Data.DataSet GetDemographicsUsingDBWithConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformationService/GetDemographicsUsingDBWithConfig", ReplyAction="http://tempuri.org/IInformationService/GetDemographicsUsingDBWithConfigResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDemographicsUsingDBWithConfigAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformationService/GetDemographicsUsingDBWithOutConfig", ReplyAction="http://tempuri.org/IInformationService/GetDemographicsUsingDBWithOutConfigRespons" +
            "e")]
        System.Data.DataSet GetDemographicsUsingDBWithOutConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformationService/GetDemographicsUsingDBWithOutConfig", ReplyAction="http://tempuri.org/IInformationService/GetDemographicsUsingDBWithOutConfigRespons" +
            "e")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDemographicsUsingDBWithOutConfigAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInformationServiceChannel : BusinessLayer.InformationService.IInformationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformationServiceClient : System.ServiceModel.ClientBase<BusinessLayer.InformationService.IInformationService>, BusinessLayer.InformationService.IInformationService {
        
        public InformationServiceClient() {
        }
        
        public InformationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InformationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDemographicsUsingDBWithConfig() {
            return base.Channel.GetDemographicsUsingDBWithConfig();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDemographicsUsingDBWithConfigAsync() {
            return base.Channel.GetDemographicsUsingDBWithConfigAsync();
        }
        
        public System.Data.DataSet GetDemographicsUsingDBWithOutConfig() {
            return base.Channel.GetDemographicsUsingDBWithOutConfig();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDemographicsUsingDBWithOutConfigAsync() {
            return base.Channel.GetDemographicsUsingDBWithOutConfigAsync();
        }
    }
}
